## Preprocessing chunks of datasets of pressure levels and wind+blh data

In [1]:
import pandas as pd

In [2]:
import pandas as pd
import xarray as xr
import numpy as np

In [90]:
ds = xr.open_dataset('/Users/meetdave/Public/AqiPred/Weather data from copernicus CDS (chunks)/ERA5 hourly data on pressure levels/data_stream-oper_stepType-instant.nc pr9', engine = 'netcdf4')
df = ds.to_dataframe()

In [93]:
df.head()

  valid_time  pressure_level  latitude  longitude           t  number expver
0 2024-01-01          1000.0      30.0      68.00  291.593994       0   0001
1 2024-01-01          1000.0      30.0      68.25  291.906494       0   0001
2 2024-01-01          1000.0      30.0      68.50  291.513916       0   0001
3 2024-01-01          1000.0      30.0      68.75  290.166260       0   0001
4 2024-01-01          1000.0      30.0      69.00  290.177979       0   0001

In [92]:
#drop=true removes data as well
df.reset_index(inplace = True)

In [ ]:
df.drop(columns = ['index'], inplace=True)

In [95]:
df.head()

  valid_time  pressure_level  latitude  longitude           t
0 2024-01-01          1000.0      30.0      68.00  291.593994
1 2024-01-01          1000.0      30.0      68.25  291.906494
2 2024-01-01          1000.0      30.0      68.50  291.513916
3 2024-01-01          1000.0      30.0      68.75  290.166260
4 2024-01-01          1000.0      30.0      69.00  290.177979

In [94]:
#remove 'number', and 'expver' 

df.drop(columns = ['number','expver'], inplace=True)

In [96]:
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 51771656 entries, 0 to 51771655
Data columns (total 5 columns):
 #   Column          Dtype
---  ------          -----
 0   valid_time      datetime64[ns]
 1   pressure_level  float64
 2   latitude        float64
 3   longitude       float64
 4   t               float32
dtypes: datetime64[ns](1), float32(1), float64(3)
memory usage: 1.7 GB

  valid_time  pressure_level  latitude  longitude           t
0 2024-01-01          1000.0      30.0      68.00  291.593994
1 2024-01-01          1000.0      30.0      68.25  291.906494
2 2024-01-01          1000.0      30.0      68.50  291.513916
3 2024-01-01          1000.0      30.0      68.75  290.166260
4 2024-01-01          1000.0      30.0      69.00  290.177979

In [99]:
#check for 2026 values
index_to_drop = [(df['valid_time'].dt.year == 2026).sum()]
print(index_to_drop)

[0]

In [98]:
#Remove 2026 values
df.drop(df[df['valid_time'].dt.year == 2026].index, inplace=True)

In [101]:
#filtering data based on cities's coordinates

ahd_mask = df[
    (df['latitude'] >= 22.89) & (df['latitude'] <= 23.16) & (df['longitude'] >= 72.44) & (df['longitude'] <= 72.71)
]

In [106]:
ahd_mask.info()
ahd_mask.head()

<class 'pandas.DataFrame'>
RangeIndex: 5848 entries, 0 to 5847
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   valid_time      5848 non-null   datetime64[ns]
 1   pressure_level  5848 non-null   float32
 2   latitude        5848 non-null   float32
 3   longitude       5848 non-null   float32
 4   t               5848 non-null   float32
dtypes: datetime64[ns](1), float32(4)
memory usage: 137.2 KB

           valid_time  pressure_level  latitude  longitude           t
0 2024-01-01 00:00:00          1000.0      23.0       72.5  291.613525
1 2024-01-01 00:00:00           950.0      23.0       72.5  292.664062
2 2024-01-01 06:00:00          1000.0      23.0       72.5  295.890625
3 2024-01-01 06:00:00           950.0      23.0       72.5  291.856201
4 2024-01-01 12:00:00          1000.0      23.0       72.5  298.466553

In [103]:
ahd_mask.reset_index(inplace = True, drop=True)

In [105]:
#slashing datatypes to lighten the data
#for time, we will convert it into total hours spent later

ahd_mask['pressure_level']= ahd_mask['pressure_level'].astype('float32')
ahd_mask['latitude']= ahd_mask['latitude'].astype('float32')
ahd_mask['longitude']= ahd_mask['longitude'].astype('float32')

In [109]:
ahd_mask.to_pickle('/Users/meetdave/Public/AqiPred/ahd_pkl_pressure/ahd_24.pkl')

In [110]:
del df, ds, ahd_mask

### Integrating ahmedabad data

In [112]:
df1 = pd.read_pickle('/Users/meetdave/Public/AqiPred/ahd_pkl_pressure/ahd_00.pkl')
df2 = pd.read_pickle('/Users/meetdave/Public/AqiPred/ahd_pkl_pressure/ahd_03.pkl')
df3 = pd.read_pickle('/Users/meetdave/Public/AqiPred/ahd_pkl_pressure/ahd_06.pkl')
df4 = pd.read_pickle('/Users/meetdave/Public/AqiPred/ahd_pkl_pressure/ahd_09.pkl')
df5 = pd.read_pickle('/Users/meetdave/Public/AqiPred/ahd_pkl_pressure/ahd_12.pkl')
df6 = pd.read_pickle('/Users/meetdave/Public/AqiPred/ahd_pkl_pressure/ahd_15.pkl')
df7 = pd.read_pickle('/Users/meetdave/Public/AqiPred/ahd_pkl_pressure/ahd_18.pkl')
df8 = pd.read_pickle('/Users/meetdave/Public/AqiPred/ahd_pkl_pressure/ahd_21.pkl')
df9 = pd.read_pickle('/Users/meetdave/Public/AqiPred/ahd_pkl_pressure/ahd_24.pkl')

In [132]:
df = pd.concat([df1, df2, df3 ,df4, df5, df6, df7])

In [140]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 61368 entries, 0 to 61367
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   valid_time      61368 non-null  datetime64[s]
 1   pressure_level  61368 non-null  float32
 2   latitude        61368 non-null  float32
 3   longitude       61368 non-null  float32
 4   t               61368 non-null  float32
dtypes: datetime64[s](1), float32(4)
memory usage: 1.4 MB

In [134]:
df.reset_index(inplace=True)

In [137]:
df.head(10)

           valid_time  pressure_level  latitude  longitude           t
0 2000-01-01 00:00:00          1000.0      23.0       72.5  290.398682
1 2000-01-01 00:00:00           950.0      23.0       72.5  294.711182
2 2000-01-01 06:00:00          1000.0      23.0       72.5  296.611328
3 2000-01-01 06:00:00           950.0      23.0       72.5  294.392578
4 2000-01-01 12:00:00          1000.0      23.0       72.5  301.278564
5 2000-01-01 12:00:00           950.0      23.0       72.5  296.894287
6 2000-01-01 18:00:00          1000.0      23.0       72.5  296.512451
7 2000-01-01 18:00:00           950.0      23.0       72.5  296.448486
8 2000-01-02 00:00:00          1000.0      23.0       72.5  290.831299
9 2000-01-02 00:00:00           950.0      23.0       72.5  295.828125

In [136]:
df.drop(columns = ['index'], inplace=True)

In [138]:
df['valid_time'] = pd.to_datetime(df['valid_time']).dt.floor('h')

In [139]:
df['valid_time'] = df['valid_time'].values.astype('datetime64[h]')

In [124]:
df.to_pickle('Press.pkl')

### Pivoting data

In [141]:
df = df.sort_values(by=['valid_time', 'pressure_level'])

In [142]:
df.head()

           valid_time  pressure_level  latitude  longitude           t
1 2000-01-01 00:00:00           950.0      23.0       72.5  294.711182
0 2000-01-01 00:00:00          1000.0      23.0       72.5  290.398682
3 2000-01-01 06:00:00           950.0      23.0       72.5  294.392578
2 2000-01-01 06:00:00          1000.0      23.0       72.5  296.611328
5 2000-01-01 12:00:00           950.0      23.0       72.5  296.894287

In [143]:
pdf = df.pivot(
    index=['valid_time', 'latitude', 'longitude'], 
    columns='pressure_level', 
    values='t'
)

In [149]:
pdf.head()

pressure_level,valid_time,latitude,longitude,950.0,1000.0
0,2000-01-01 00:00:00,23.0,72.5,294.711182,290.398682
1,2000-01-01 06:00:00,23.0,72.5,294.392578,296.611328
2,2000-01-01 12:00:00,23.0,72.5,296.894287,301.278564
3,2000-01-01 18:00:00,23.0,72.5,296.448486,296.512451
4,2000-01-02 00:00:00,23.0,72.5,295.828125,290.831299

In [146]:
pdf.reset_index(inplace=True)

In [150]:
pdf.info()

<class 'pandas.DataFrame'>
RangeIndex: 30684 entries, 0 to 30683
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   valid_time  30684 non-null  datetime64[s]
 1   latitude    30684 non-null  float32
 2   longitude   30684 non-null  float32
 3   950.0       30684 non-null  float32
 4   1000.0      30684 non-null  float32
dtypes: datetime64[s](1), float32(4)
memory usage: 719.3 KB

### Making Features and Combining both datasets

In [153]:
pdf.head()

pressure_level,valid_time,latitude,longitude,950 hpa,1000 hpa
0,2000-01-01 00:00:00,23.0,72.5,294.711182,290.398682
1,2000-01-01 06:00:00,23.0,72.5,294.392578,296.611328
2,2000-01-01 12:00:00,23.0,72.5,296.894287,301.278564
3,2000-01-01 18:00:00,23.0,72.5,296.448486,296.512451
4,2000-01-02 00:00:00,23.0,72.5,295.828125,290.831299

In [152]:
pdf = pdf.rename(columns = {950.0 : '950 hpa', 1000.0: '1000 hpa'})

####  For surface data
-Pressure data is already in ``` pdf ```

In [154]:
sdf = pd.read_pickle('/Users/meetdave/Public/AqiPred/Final_wblh.pkl')

In [159]:
sdf.info()

<class 'pandas.DataFrame'>
RangeIndex: 37988 entries, 0 to 37987
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   valid_time  37988 non-null  datetime64[s]
 1   latitude    37988 non-null  float32
 2   longitude   37988 non-null  float32
 3   u10         37988 non-null  float32
 4   v10         37988 non-null  float32
 5   blh         37988 non-null  float32
dtypes: datetime64[s](1), float32(5)
memory usage: 1.0 MB

In [156]:
sdf.head()

           valid_time  latitude  longitude       u10       v10         blh
0 2000-01-01 00:00:00      23.0       72.5 -2.187836 -1.273849   90.085373
1 2000-01-01 06:00:00      23.0       72.5 -3.442169 -0.297363  473.053375
2 2000-01-01 12:00:00      23.0       72.5 -0.763641 -1.044540   55.727810
3 2000-01-01 18:00:00      23.0       72.5 -1.532761 -1.577179   63.075550
4 2000-01-02 00:00:00      23.0       72.5 -3.265732 -1.134567  169.401291

#### Merging surface data and pressure data

In [157]:

Mod1 = pd.merge(sdf, pdf, on=['valid_time', 'latitude', 'longitude'], how= 'inner')

In [185]:
Mod1.head(7)

,blh,wind_speed,temp_gradient,hour,month,blh_lag_6h,wind_lag_6h
valid_time,,,,,,,
2000-01-01 00:00:00,90.085373,2.531663,4.312500,0,1,NaN,NaN
2000-01-01 06:00:00,473.053375,3.454990,-2.218750,6,1,90.085373,2.531663
2000-01-01 12:00:00,55.727810,1.293914,-4.384277,12,1,473.053375,3.454990
2000-01-01 18:00:00,63.075550,2.199284,-0.063965,18,1,55.727810,1.293914
2000-01-02 00:00:00,169.401291,3.457202,4.996826,0,1,63.075550,2.199284
2000-01-02 06:00:00,456.368317,3.458246,-2.028809,6,1,169.401291,3.457202
2000-01-02 12:00:00,131.031219,1.656585,-4.355225,12,1,456.368317,3.458246

In [186]:
Mod1.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 30684 entries, 2000-01-01 00:00:00 to 2020-12-31 18:00:00
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   blh            30684 non-null  float32
 1   wind_speed     30684 non-null  float32
 2   temp_gradient  30684 non-null  float32
 3   hour           30684 non-null  int32
 4   month          30684 non-null  int32
 5   blh_lag_6h     30683 non-null  float32
 6   wind_lag_6h    30683 non-null  float32
dtypes: float32(5), int32(2)
memory usage: 1.1 MB

In [161]:
# Wind Speed Magnitude (Pythagorean theorem)

Mod1['wind_speed'] = np.sqrt(Mod1['u10']**2 + Mod1['v10']**2)

In [163]:
# Temperature Gradient (Upper temp minus Lower temp)

Mod1['temp_gradient'] = Mod1['950 hpa'] - Mod1['1000 hpa']

In [165]:
# Extracting 'hour' (0-23) and 'month' (1-12)

Mod1['hour'] = Mod1['valid_time'].dt.hour
Mod1['month'] = Mod1['valid_time'].dt.month

In [167]:
# Lagged blh and wind data
# Shift down by 1 row (representing a 6-hour lag)

Mod1['blh_lag_6h'] = Mod1['blh'].shift(1)
Mod1['wind_lag_6h'] = Mod1['wind_speed'].shift(1)

In [169]:
#cleaning

Mod1.drop(columns = ['u10', 'v10', '950 hpa', '1000 hpa', 'latitude', 'longitude'], inplace=True)

#removed a null row

In [184]:
Mod1 = Mod1.set_index('valid_time')

In [187]:
Mod1.to_pickle('Mod1Set_ahd.pkl')